package be.pxl.publictms.pojo;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA



/**
 * Actie generated by hbm2java
 */
public class Actie  implements java.io.Serializable {


     private int actieid;
     private Transportadres transportadres;
     private Opdracht opdracht;
     private Boolean actieklaar;
     private String lading;
     private String vrijveld;

    public Actie() {
    }

	
    public Actie(int actieid, Transportadres transportadres, Opdracht opdracht) {
        this.actieid = actieid;
        this.transportadres = transportadres;
        this.opdracht = opdracht;
    }
    public Actie(int actieid, Transportadres transportadres, Opdracht opdracht, Boolean actieklaar, String lading, String vrijveld) {
       this.actieid = actieid;
       this.transportadres = transportadres;
       this.opdracht = opdracht;
       this.actieklaar = actieklaar;
       this.lading = lading;
       this.vrijveld = vrijveld;
    }
   
    public int getActieid() {
        return this.actieid;
    }
    
    public void setActieid(int actieid) {
        this.actieid = actieid;
    }
    public Transportadres getTransportadres() {
        return this.transportadres;
    }
    
    public void setTransportadres(Transportadres transportadres) {
        this.transportadres = transportadres;
    }
    public Opdracht getOpdracht() {
        return this.opdracht;
    }
    
    public void setOpdracht(Opdracht opdracht) {
        this.opdracht = opdracht;
    }
    public Boolean getActieklaar() {
        return this.actieklaar;
    }
    
    public void setActieklaar(Boolean actieklaar) {
        this.actieklaar = actieklaar;
    }
    public String getLading() {
        return this.lading;
    }
    
    public void setLading(String lading) {
        this.lading = lading;
    }
    public String getVrijveld() {
        return this.vrijveld;
    }
    
    public void setVrijveld(String vrijveld) {
        this.vrijveld = vrijveld;
    }




}


