package be.pxl.publictms.pojo;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Adres generated by hbm2java
 */
public class Adres  implements java.io.Serializable {


     private int adresid;
     private Postcode postcode;
     private String straat;
     private short nummer;
     private String bus;
     private String land;
     private Set<Transportadres> transportadreses = new HashSet<Transportadres>(0);
     private Set<Facturatie> facturaties = new HashSet<Facturatie>(0);

    public Adres() {
    }

	
    public Adres(int adresid, Postcode postcode, String straat, short nummer, String land) {
        this.adresid = adresid;
        this.postcode = postcode;
        this.straat = straat;
        this.nummer = nummer;
        this.land = land;
    }
    public Adres(int adresid, Postcode postcode, String straat, short nummer, String bus, String land, Set<Transportadres> transportadreses, Set<Facturatie> facturaties) {
       this.adresid = adresid;
       this.postcode = postcode;
       this.straat = straat;
       this.nummer = nummer;
       this.bus = bus;
       this.land = land;
       this.transportadreses = transportadreses;
       this.facturaties = facturaties;
    }
   
    public int getAdresid() {
        return this.adresid;
    }
    
    public void setAdresid(int adresid) {
        this.adresid = adresid;
    }
    public Postcode getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(Postcode postcode) {
        this.postcode = postcode;
    }
    public String getStraat() {
        return this.straat;
    }
    
    public void setStraat(String straat) {
        this.straat = straat;
    }
    public short getNummer() {
        return this.nummer;
    }
    
    public void setNummer(short nummer) {
        this.nummer = nummer;
    }
    public String getBus() {
        return this.bus;
    }
    
    public void setBus(String bus) {
        this.bus = bus;
    }
    public String getLand() {
        return this.land;
    }
    
    public void setLand(String land) {
        this.land = land;
    }
    public Set<Transportadres> getTransportadreses() {
        return this.transportadreses;
    }
    
    public void setTransportadreses(Set<Transportadres> transportadreses) {
        this.transportadreses = transportadreses;
    }
    public Set<Facturatie> getFacturaties() {
        return this.facturaties;
    }
    
    public void setFacturaties(Set<Facturatie> facturaties) {
        this.facturaties = facturaties;
    }




}


