package be.pxl.publictms.pojo;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA



/**
 * Facturatie generated by hbm2java
 */
public class Facturatie  implements java.io.Serializable {


     private int facturatieid;
     private Adres adres;
     private Klant klant;
     private String munt;
     private String btwregime;
     private String btwnummer;
     private String ondernemingsnummer;
     private String iban;
     private String bic;
     private String betalingscondities;
     private String vrijveld;
     private Double prijsgegeven;

    public Facturatie() {
    }

	
    public Facturatie(int facturatieid, Adres adres, Klant klant) {
        this.facturatieid = facturatieid;
        this.adres = adres;
        this.klant = klant;
    }
    public Facturatie(int facturatieid, Adres adres, Klant klant, String munt, String btwregime, String btwnummer, String ondernemingsnummer, String iban, String bic, String betalingscondities, String vrijveld, Double prijsgegeven) {
       this.facturatieid = facturatieid;
       this.adres = adres;
       this.klant = klant;
       this.munt = munt;
       this.btwregime = btwregime;
       this.btwnummer = btwnummer;
       this.ondernemingsnummer = ondernemingsnummer;
       this.iban = iban;
       this.bic = bic;
       this.betalingscondities = betalingscondities;
       this.vrijveld = vrijveld;
       this.prijsgegeven = prijsgegeven;
    }
   
    public int getFacturatieid() {
        return this.facturatieid;
    }
    
    public void setFacturatieid(int facturatieid) {
        this.facturatieid = facturatieid;
    }
    public Adres getAdres() {
        return this.adres;
    }
    
    public void setAdres(Adres adres) {
        this.adres = adres;
    }
    public Klant getKlant() {
        return this.klant;
    }
    
    public void setKlant(Klant klant) {
        this.klant = klant;
    }
    public String getMunt() {
        return this.munt;
    }
    
    public void setMunt(String munt) {
        this.munt = munt;
    }
    public String getBtwregime() {
        return this.btwregime;
    }
    
    public void setBtwregime(String btwregime) {
        this.btwregime = btwregime;
    }
    public String getBtwnummer() {
        return this.btwnummer;
    }
    
    public void setBtwnummer(String btwnummer) {
        this.btwnummer = btwnummer;
    }
    public String getOndernemingsnummer() {
        return this.ondernemingsnummer;
    }
    
    public void setOndernemingsnummer(String ondernemingsnummer) {
        this.ondernemingsnummer = ondernemingsnummer;
    }
    public String getIban() {
        return this.iban;
    }
    
    public void setIban(String iban) {
        this.iban = iban;
    }
    public String getBic() {
        return this.bic;
    }
    
    public void setBic(String bic) {
        this.bic = bic;
    }
    public String getBetalingscondities() {
        return this.betalingscondities;
    }
    
    public void setBetalingscondities(String betalingscondities) {
        this.betalingscondities = betalingscondities;
    }
    public String getVrijveld() {
        return this.vrijveld;
    }
    
    public void setVrijveld(String vrijveld) {
        this.vrijveld = vrijveld;
    }
    public Double getPrijsgegeven() {
        return this.prijsgegeven;
    }
    
    public void setPrijsgegeven(Double prijsgegeven) {
        this.prijsgegeven = prijsgegeven;
    }




}


