package be.pxl.publictms.pojo;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Gebruiker generated by hbm2java
 */
public class Gebruiker  implements java.io.Serializable {


     private int gebruikerid;
     private Werknemer werknemer;
     private String gebruikersnaam;
     private String paswoord;
     private Set<Bericht> berichtsForGebruikerid = new HashSet<Bericht>(0);
     private Set<Bericht> berichtsForOntvangerid = new HashSet<Bericht>(0);
    public Gebruiker() {
    }

	
    public Gebruiker(int gebruikerid, String gebruikersnaam, String paswoord) {
        this.gebruikerid = gebruikerid;
        this.gebruikersnaam = gebruikersnaam;
        this.paswoord = paswoord;
    }
    public Gebruiker(int gebruikerid, Werknemer werknemer, String gebruikersnaam, String paswoord, Set<Bericht> berichtsForGebruikerid, Set<Bericht> berichtsForOntvangerid) {
       this.gebruikerid = gebruikerid;
       this.werknemer = werknemer;
       this.gebruikersnaam = gebruikersnaam;
       this.paswoord = paswoord;
       this.berichtsForGebruikerid = berichtsForGebruikerid;
       this.berichtsForOntvangerid = berichtsForOntvangerid;
    }
   
    public int getGebruikerid() {
        return this.gebruikerid;
    }
    
    public void setGebruikerid(int gebruikerid) {
        this.gebruikerid = gebruikerid;
    }
    public Werknemer getWerknemer() {
        return this.werknemer;
    }
    
    public void setWerknemer(Werknemer werknemer) {
        this.werknemer = werknemer;
    }
    public String getGebruikersnaam() {
        return this.gebruikersnaam;
    }
    
    public void setGebruikersnaam(String gebruikersnaam) {
        this.gebruikersnaam = gebruikersnaam;
    }
    public String getPaswoord() {
        return this.paswoord;
    }
    
    public void setPaswoord(String paswoord) {
        this.paswoord = paswoord;
    }
    public Set<Bericht> getBerichtsForGebruikerid() {
        return this.berichtsForGebruikerid;
    }
    
    public void setBerichtsForGebruikerid(Set<Bericht> berichtsForGebruikerid) {
        this.berichtsForGebruikerid = berichtsForGebruikerid;
    }
    public Set<Bericht> getBerichtsForOntvangerid() {
        return this.berichtsForOntvangerid;
    }
    
    public void setBerichtsForOntvangerid(Set<Bericht> berichtsForOntvangerid) {
        this.berichtsForOntvangerid = berichtsForOntvangerid;
    }
    @Override
    public String toString(){
        return this.gebruikersnaam + " " + this.paswoord;
    }
}


