package be.pxl.publictms.pojo;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Opdracht generated by hbm2java
 */
public class Opdracht  implements java.io.Serializable {


     private int opdrachtid;
     private Voertuig voertuig;
     private Werknemer werknemer;
     private Oplegger oplegger;
     private int klantid;
     private Date datum;
     private Boolean opdrachtklaar;
     private String vrijveld;
     private Set<Actie> acties = new HashSet<Actie>(0);

    public Opdracht() {
    }

	
    public Opdracht(int opdrachtid, int klantid) {
        this.opdrachtid = opdrachtid;
        this.klantid = klantid;
    }
    public Opdracht(int opdrachtid, Voertuig voertuig, Werknemer werknemer, Oplegger oplegger, int klantid, Date datum, Boolean opdrachtklaar, String vrijveld, Set<Actie> acties) {
       this.opdrachtid = opdrachtid;
       this.voertuig = voertuig;
       this.werknemer = werknemer;
       this.oplegger = oplegger;
       this.klantid = klantid;
       this.datum = datum;
       this.opdrachtklaar = opdrachtklaar;
       this.vrijveld = vrijveld;
       this.acties = acties;
    }
   
    public int getOpdrachtid() {
        return this.opdrachtid;
    }
    
    public void setOpdrachtid(int opdrachtid) {
        this.opdrachtid = opdrachtid;
    }
    public Voertuig getVoertuig() {
        return this.voertuig;
    }
    
    public void setVoertuig(Voertuig voertuig) {
        this.voertuig = voertuig;
    }
    public Werknemer getWerknemer() {
        return this.werknemer;
    }
    
    public void setWerknemer(Werknemer werknemer) {
        this.werknemer = werknemer;
    }
    public Oplegger getOplegger() {
        return this.oplegger;
    }
    
    public void setOplegger(Oplegger oplegger) {
        this.oplegger = oplegger;
    }
    public int getKlantid() {
        return this.klantid;
    }
    
    public void setKlantid(int klantid) {
        this.klantid = klantid;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public Boolean getOpdrachtklaar() {
        return this.opdrachtklaar;
    }
    
    public void setOpdrachtklaar(Boolean opdrachtklaar) {
        this.opdrachtklaar = opdrachtklaar;
    }
    public String getVrijveld() {
        return this.vrijveld;
    }
    
    public void setVrijveld(String vrijveld) {
        this.vrijveld = vrijveld;
    }
    public Set<Actie> getActies() {
        return this.acties;
    }
    
    public void setActies(Set<Actie> acties) {
        this.acties = acties;
    }




}


