package be.pxl.publictms.pojo;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Oplegger generated by hbm2java
 */
public class Oplegger  implements java.io.Serializable {


     private int opleggerid;
     private Laadgegevens laadgegevens;
     private String nummerplaat;
     private Boolean actief;
     private String omschrijving;
     private String opleggertype;
     private String bouwjaar;
     private Date datumingebruik;
     private Date datumuitgebruik;
     private String chassisnummer;
     private Boolean vergunning;
     private Date vergunninggeldigtot;
     private String pvg;
     private Set<Voertuig> voertuigs = new HashSet<Voertuig>(0);
     private Set<Opdracht> opdrachts = new HashSet<Opdracht>(0);

    public Oplegger() {
    }

	
    public Oplegger(int opleggerid) {
        this.opleggerid = opleggerid;
    }
    public Oplegger(int opleggerid, Laadgegevens laadgegevens, String nummerplaat, Boolean actief, String omschrijving, String opleggertype, String bouwjaar, Date datumingebruik, Date datumuitgebruik, String chassisnummer, Boolean vergunning, Date vergunninggeldigtot, String pvg, Set<Voertuig> voertuigs, Set<Opdracht> opdrachts) {
       this.opleggerid = opleggerid;
       this.laadgegevens = laadgegevens;
       this.nummerplaat = nummerplaat;
       this.actief = actief;
       this.omschrijving = omschrijving;
       this.opleggertype = opleggertype;
       this.bouwjaar = bouwjaar;
       this.datumingebruik = datumingebruik;
       this.datumuitgebruik = datumuitgebruik;
       this.chassisnummer = chassisnummer;
       this.vergunning = vergunning;
       this.vergunninggeldigtot = vergunninggeldigtot;
       this.pvg = pvg;
       this.voertuigs = voertuigs;
       this.opdrachts = opdrachts;
    }
   
    public int getOpleggerid() {
        return this.opleggerid;
    }
    
    public void setOpleggerid(int opleggerid) {
        this.opleggerid = opleggerid;
    }
    public Laadgegevens getLaadgegevens() {
        return this.laadgegevens;
    }
    
    public void setLaadgegevens(Laadgegevens laadgegevens) {
        this.laadgegevens = laadgegevens;
    }
    public String getNummerplaat() {
        return this.nummerplaat;
    }
    
    public void setNummerplaat(String nummerplaat) {
        this.nummerplaat = nummerplaat;
    }
    public Boolean getActief() {
        return this.actief;
    }
    
    public void setActief(Boolean actief) {
        this.actief = actief;
    }
    public String getOmschrijving() {
        return this.omschrijving;
    }
    
    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }
    public String getOpleggertype() {
        return this.opleggertype;
    }
    
    public void setOpleggertype(String opleggertype) {
        this.opleggertype = opleggertype;
    }
    public String getBouwjaar() {
        return this.bouwjaar;
    }
    
    public void setBouwjaar(String bouwjaar) {
        this.bouwjaar = bouwjaar;
    }
    public Date getDatumingebruik() {
        return this.datumingebruik;
    }
    
    public void setDatumingebruik(Date datumingebruik) {
        this.datumingebruik = datumingebruik;
    }
    public Date getDatumuitgebruik() {
        return this.datumuitgebruik;
    }
    
    public void setDatumuitgebruik(Date datumuitgebruik) {
        this.datumuitgebruik = datumuitgebruik;
    }
    public String getChassisnummer() {
        return this.chassisnummer;
    }
    
    public void setChassisnummer(String chassisnummer) {
        this.chassisnummer = chassisnummer;
    }
    public Boolean getVergunning() {
        return this.vergunning;
    }
    
    public void setVergunning(Boolean vergunning) {
        this.vergunning = vergunning;
    }
    public Date getVergunninggeldigtot() {
        return this.vergunninggeldigtot;
    }
    
    public void setVergunninggeldigtot(Date vergunninggeldigtot) {
        this.vergunninggeldigtot = vergunninggeldigtot;
    }
    public String getPvg() {
        return this.pvg;
    }
    
    public void setPvg(String pvg) {
        this.pvg = pvg;
    }
    public Set<Voertuig> getVoertuigs() {
        return this.voertuigs;
    }
    
    public void setVoertuigs(Set<Voertuig> voertuigs) {
        this.voertuigs = voertuigs;
    }
    public Set<Opdracht> getOpdrachts() {
        return this.opdrachts;
    }
    
    public void setOpdrachts(Set<Opdracht> opdrachts) {
        this.opdrachts = opdrachts;
    }




}


