package be.pxl.publictms.pojo;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Postcode generated by hbm2java
 */
public class Postcode  implements java.io.Serializable {


     private String postcode;
     private String gemeente;
     private Set<Adres> adreses = new HashSet<Adres>(0);

    public Postcode() {
    }

	
    public Postcode(String postcode, String gemeente) {
        this.postcode = postcode;
        this.gemeente = gemeente;
    }
    public Postcode(String postcode, String gemeente, Set<Adres> adreses) {
       this.postcode = postcode;
       this.gemeente = gemeente;
       this.adreses = adreses;
    }
   
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public String getGemeente() {
        return this.gemeente;
    }
    
    public void setGemeente(String gemeente) {
        this.gemeente = gemeente;
    }
    public Set<Adres> getAdreses() {
        return this.adreses;
    }
    
    public void setAdreses(Set<Adres> adreses) {
        this.adreses = adreses;
    }




}


