package be.pxl.publictms.pojo;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Transportadres generated by hbm2java
 */
public class Transportadres  implements java.io.Serializable {


     private int transportid;
     private Adres adres;
     private Contact contact;
     private Taal taal;
     private String naam;
     private Boolean actief;
     private String soortadres;
     private String vensteruren;
     private String vrachtbeperking;
     private String chauffeursbeperking;
     private String vrijveld;
     private Set<Actie> acties = new HashSet<Actie>(0);

    public Transportadres() {
    }

	
    public Transportadres(int transportid, Adres adres, Contact contact) {
        this.transportid = transportid;
        this.adres = adres;
        this.contact = contact;
    }
    public Transportadres(int transportid, Adres adres, Contact contact, Taal taal, String naam, Boolean actief, String soortadres, String vensteruren, String vrachtbeperking, String chauffeursbeperking, String vrijveld, Set<Actie> acties) {
       this.transportid = transportid;
       this.adres = adres;
       this.contact = contact;
       this.taal = taal;
       this.naam = naam;
       this.actief = actief;
       this.soortadres = soortadres;
       this.vensteruren = vensteruren;
       this.vrachtbeperking = vrachtbeperking;
       this.chauffeursbeperking = chauffeursbeperking;
       this.vrijveld = vrijveld;
       this.acties = acties;
    }
   
    public int getTransportid() {
        return this.transportid;
    }
    
    public void setTransportid(int transportid) {
        this.transportid = transportid;
    }
    public Adres getAdres() {
        return this.adres;
    }
    
    public void setAdres(Adres adres) {
        this.adres = adres;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }
    public Taal getTaal() {
        return this.taal;
    }
    
    public void setTaal(Taal taal) {
        this.taal = taal;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public Boolean getActief() {
        return this.actief;
    }
    
    public void setActief(Boolean actief) {
        this.actief = actief;
    }
    public String getSoortadres() {
        return this.soortadres;
    }
    
    public void setSoortadres(String soortadres) {
        this.soortadres = soortadres;
    }
    public String getVensteruren() {
        return this.vensteruren;
    }
    
    public void setVensteruren(String vensteruren) {
        this.vensteruren = vensteruren;
    }
    public String getVrachtbeperking() {
        return this.vrachtbeperking;
    }
    
    public void setVrachtbeperking(String vrachtbeperking) {
        this.vrachtbeperking = vrachtbeperking;
    }
    public String getChauffeursbeperking() {
        return this.chauffeursbeperking;
    }
    
    public void setChauffeursbeperking(String chauffeursbeperking) {
        this.chauffeursbeperking = chauffeursbeperking;
    }
    public String getVrijveld() {
        return this.vrijveld;
    }
    
    public void setVrijveld(String vrijveld) {
        this.vrijveld = vrijveld;
    }
    public Set<Actie> getActies() {
        return this.acties;
    }
    
    public void setActies(Set<Actie> acties) {
        this.acties = acties;
    }




}


